# Generated by Django 5.1.1 on 2024-10-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GRAPHICS", "Graphics & Design"),
                            ("TECH", "Programming & Tech"),
                            ("MARKETING", "Digital Marketing"),
                            ("VIDEO", "Video & Animation"),
                            ("WRITING", "Writing & Translation"),
                            ("MUSIC", "Music & Audio"),
                            ("BUSINESS", "Business"),
                            ("FINANCE", "Finance"),
                            ("AI", "AI Services"),
                            ("GROWTH", "Personal Growth"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GRAPHICS", "Graphics & Design"),
                            ("TECH", "Programming & Tech"),
                            ("MARKETING", "Digital Marketing"),
                            ("VIDEO", "Video & Animation"),
                            ("WRITING", "Writing & Translation"),
                            ("MUSIC", "Music & Audio"),
                            ("BUSINESS", "Business"),
                            ("FINANCE", "Finance"),
                            ("AI", "AI Services"),
                            ("GROWTH", "Personal Growth"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("password_hash", models.TextField()),
                ("multiplier", models.FloatField(default=1.0)),
                ("avg_rating", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="ListingAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_time", models.DateTimeField()),
                ("to_time", models.DateTimeField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Time_Banking.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("status", models.SmallIntegerField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Time_Banking.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Time_Banking.user",
                    ),
                ),
            ],
        ),
    ]
