# Generated by Django 5.1.2 on 2024-11-02 16:28

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.BooleanField(
                choices=[(True, 'Offer'), (False, 'Request')], default=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='posted_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(to='Time_Banking.tag'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
