# Generated by Django 5.1.1 on 2024-11-13 18:46

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Time_Banking",
            "0002_listing_creator_listing_duration_listing_edited_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(blank=True, upload_to="static/images/user"),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
