# Generated by Django 5.1.1 on 2024-11-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Time_Banking", "0003_alter_listing_creator_alter_listing_duration_and_more"),
        ("Time_Banking", "0003_listing_status_alter_listing_creator_and_more"),
    ]

    operations = []
