# Generated by Django 5.1.2 on 2024-11-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Banking', '0004_merge_20241116_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(
                choices=[(True, 'Offer'), (False, 'Request')], max_length=10, null=True
            ),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
