# Generated by Django 5.1.1 on 2024-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Time_Banking", "0005_alter_listing_listing_type_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.TextField(default="/#"),
        ),
    ]
