# Generated by Django 5.1.1 on 2024-12-04 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0004_skill_alter_listing_creator_and_more"),
        ("Time_Banking", "0007_alter_notification_url"),
    ]

    operations = []
