# Generated by Django 5.1.1 on 2024-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Time_Banking", "0008_merge_20241204_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingresponse",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
