# Generated by Django 5.1.1 on 2024-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Time_Banking", "0009_listingresponse_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="static/images/profile_default.png",
                upload_to="static/images/user",
            ),
        ),
    ]
