# Generated by Django 5.1.1 on 2024-12-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Time_Banking", "0009_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
