# Generated by Django 5.1.1 on 2024-12-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Time_Banking", "0010_alter_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(blank=True, upload_to="static/images/user"),
        ),
    ]
