# Generated by Django 5.1.1 on 2024-12-16 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0009_user_total_minutes_servicetransaction_feedback"),
        ("Time_Banking", "0011_alter_user_picture"),
    ]

    operations = []
