# Generated by Django 5.1.1 on 2024-12-18 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0010_alter_review_unique_together"),
        ("Time_Banking", "0012_merge_20241216_1745"),
    ]

    operations = []
