# Generated by Django 5.1.1 on 2024-12-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0012_merge_20241216_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
