# Generated by Django 5.1.1 on 2024-12-18 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0013_feedback_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True
            ),
        ),
    ]
