# Generated by Django 5.1.1 on 2024-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0014_feedback_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingresponse",
            name="feedback_given",
            field=models.BooleanField(default=False),
        ),
    ]
