# Generated by Django 5.1.1 on 2024-12-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Time_Banking", "0015_listingresponse_feedback_given"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
